/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package protitipo_aplicacion_innovatec;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user1
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla_CreacionLibro = new javax.swing.JFrame();
        cb_barCodeLibro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tf_nombreLibro = new javax.swing.JTextField();
        cb_Materia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descrpcionLibro = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jb_añadirLibro_A_Inventario = new javax.swing.JButton();
        pantalla_EliminarLibro = new javax.swing.JFrame();
        cb_barCodeLibroEliminar = new javax.swing.JComboBox<>();
        tf_nombreLibroDelete = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLibro = new javax.swing.JMenu();
        menuItem_loadCSV = new javax.swing.JMenuItem();
        menuItem_agregarLibro = new javax.swing.JMenuItem();
        menuItem_edLibri = new javax.swing.JMenuItem();
        menu_readLibros = new javax.swing.JMenu();
        menuItem_readLibrosLectura = new javax.swing.JMenuItem();
        menuItem_readLibrosAprenidzaje = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        menuItem_newPrestamo = new javax.swing.JMenuItem();
        menuItem_devolverLibro = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuAlumno = new javax.swing.JMenu();
        menuItem_createAlumno = new javax.swing.JMenuItem();
        menuItem_modAlumno = new javax.swing.JMenuItem();
        menuItem_createMaestro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuItem_modMaestro = new javax.swing.JMenuItem();
        menuItem_listMaestros = new javax.swing.JMenuItem();

        cb_barCodeLibro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_barCodeLibroItemStateChanged(evt);
            }
        });

        jLabel1.setText("Codigo de Libro");

        cb_Materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Reading", "Spelling", "Language", "Social Studies", "Arts", "Spanish", "History", "Computer", "Science", "Civics", "Otras..." }));

        ta_descrpcionLibro.setColumns(20);
        ta_descrpcionLibro.setRows(5);
        jScrollPane1.setViewportView(ta_descrpcionLibro);

        jLabel2.setText("Descripcion del Libro");

        jb_añadirLibro_A_Inventario.setText("Añadir");
        jb_añadirLibro_A_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_añadirLibro_A_InventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantalla_CreacionLibroLayout = new javax.swing.GroupLayout(pantalla_CreacionLibro.getContentPane());
        pantalla_CreacionLibro.getContentPane().setLayout(pantalla_CreacionLibroLayout);
        pantalla_CreacionLibroLayout.setHorizontalGroup(
            pantalla_CreacionLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantalla_CreacionLibroLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(pantalla_CreacionLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantalla_CreacionLibroLayout.createSequentialGroup()
                        .addGroup(pantalla_CreacionLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantalla_CreacionLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pantalla_CreacionLibroLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(69, 69, 69)
                                    .addComponent(cb_barCodeLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(tf_nombreLibro)
                                .addComponent(cb_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantalla_CreacionLibroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(298, 298, 298))))
            .addGroup(pantalla_CreacionLibroLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jb_añadirLibro_A_Inventario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pantalla_CreacionLibroLayout.setVerticalGroup(
            pantalla_CreacionLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantalla_CreacionLibroLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pantalla_CreacionLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_barCodeLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addComponent(tf_nombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cb_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_añadirLibro_A_Inventario)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cb_barCodeLibroEliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_barCodeLibroEliminarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pantalla_EliminarLibroLayout = new javax.swing.GroupLayout(pantalla_EliminarLibro.getContentPane());
        pantalla_EliminarLibro.getContentPane().setLayout(pantalla_EliminarLibroLayout);
        pantalla_EliminarLibroLayout.setHorizontalGroup(
            pantalla_EliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantalla_EliminarLibroLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(pantalla_EliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_barCodeLibroEliminar, 0, 204, Short.MAX_VALUE)
                    .addComponent(tf_nombreLibroDelete))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        pantalla_EliminarLibroLayout.setVerticalGroup(
            pantalla_EliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantalla_EliminarLibroLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(cb_barCodeLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(tf_nombreLibroDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLibro.setText("Libros");

        menuItem_loadCSV.setText("Cargar CSV con codigos");
        menuItem_loadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_loadCSVActionPerformed(evt);
            }
        });
        menuLibro.add(menuItem_loadCSV);

        menuItem_agregarLibro.setText("Agregar Libro al Inventario");
        menuItem_agregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_agregarLibroActionPerformed(evt);
            }
        });
        menuLibro.add(menuItem_agregarLibro);

        menuItem_edLibri.setText("Eliminar Libro del Inventario");
        menuItem_edLibri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_edLibriActionPerformed(evt);
            }
        });
        menuLibro.add(menuItem_edLibri);

        menu_readLibros.setText("Ver Libros en Inventario");

        menuItem_readLibrosLectura.setText("Libros de Lectura para alumnos");
        menu_readLibros.add(menuItem_readLibrosLectura);

        menuItem_readLibrosAprenidzaje.setText("Libros para enseñanza");
        menu_readLibros.add(menuItem_readLibrosAprenidzaje);

        menuLibro.add(menu_readLibros);

        jMenuBar1.add(menuLibro);

        menuPrestamos.setText("Prestamos");

        menuItem_newPrestamo.setText("Crear nueva entrada");
        menuPrestamos.add(menuItem_newPrestamo);

        menuItem_devolverLibro.setText("Confirmar devolucion");
        menuPrestamos.add(menuItem_devolverLibro);

        jMenuBar1.add(menuPrestamos);

        menuUsuarios.setText("Usuarios");

        menuAlumno.setText("Alumnos");

        menuItem_createAlumno.setText("Crear nuevo usuario");
        menuAlumno.add(menuItem_createAlumno);

        menuItem_modAlumno.setText("Modificar/Eliminar Usuario");
        menuAlumno.add(menuItem_modAlumno);

        menuItem_createMaestro.setText("Listar alumnos en sistema");
        menuAlumno.add(menuItem_createMaestro);

        menuUsuarios.add(menuAlumno);

        jMenu1.setText("Maestro");

        jMenuItem4.setText("Crear nuevo usuario");
        jMenu1.add(jMenuItem4);

        menuItem_modMaestro.setText("Modificar/Eliminar Usuario");
        jMenu1.add(menuItem_modMaestro);

        menuItem_listMaestros.setText("Listar maestros en el sistema");
        jMenu1.add(menuItem_listMaestros);

        menuUsuarios.add(jMenu1);

        jMenuBar1.add(menuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_loadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_loadCSVActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            FileReader fr = null;
            try {
                fichero = fc.getSelectedFile();
                if (!nombresLibros.isEmpty()) {
                    nombresLibros.clear();
                }
                if (!barCodes.isEmpty()) {
                    barCodes.clear();
                }
                JOptionPane.showMessageDialog(null, "El archivo ha sido cargado exitosamente", "REALIZADO", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se pudo cargar el archivo", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuItem_loadCSVActionPerformed

    private void jb_añadirLibro_A_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_añadirLibro_A_InventarioActionPerformed
        String nombre = "", materia = "", barCode = "", descripcion = "";
        nombre = nombresLibros.get(cb_barCodeLibro.getSelectedIndex());
        materia = cb_Materia.getSelectedItem().toString();
        barCode = barCodes.get(cb_barCodeLibro.getSelectedIndex());
        descripcion = ta_descrpcionLibro.getText();
        Libro l = new Libro(barCode, nombre, materia, descripcion);
        pantalla_CreacionLibro.setVisible(false);
        int eleccion = JOptionPane.showConfirmDialog(null, "Libro ingresado. ¿Desea actualizar el sistema?", "ACTUALIZAR", JOptionPane.YES_NO_CANCEL_OPTION);
        if (eleccion == JOptionPane.YES_OPTION) {
            libros.add(l);
        }
    }//GEN-LAST:event_jb_añadirLibro_A_InventarioActionPerformed

    private void menuItem_edLibriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_edLibriActionPerformed
        DefaultComboBoxModel cbm = (DefaultComboBoxModel) cb_barCodeLibroEliminar.getModel();
        cbm.removeAllElements();
        for (int i = 0; i < libros.size(); i++) {
            cbm.addElement(libros.get(i).getBarCode());
        }
        cb_barCodeLibroEliminar.setModel(cbm);
        pantalla_EliminarLibro.pack();
        pantalla_EliminarLibro.setLocationRelativeTo(null);
        pantalla_EliminarLibro.setAlwaysOnTop(true);
        pantalla_EliminarLibro.setVisible(true);
    }//GEN-LAST:event_menuItem_edLibriActionPerformed

    private void cb_barCodeLibroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_barCodeLibroItemStateChanged
        try {
            tf_nombreLibro.setText(nombresLibros.get(cb_barCodeLibro.getSelectedIndex()));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cb_barCodeLibroItemStateChanged

    private void cb_barCodeLibroEliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_barCodeLibroEliminarItemStateChanged
        try {
            tf_nombreLibroDelete.setText(nombresLibros.get(cb_barCodeLibroEliminar.getSelectedIndex()));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cb_barCodeLibroEliminarItemStateChanged

    private void menuItem_agregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_agregarLibroActionPerformed
        if (fichero.isFile()) {
            try {
                FileReader fr = null;
                fr = new FileReader(fichero);
                BufferedReader br = new BufferedReader(fr);
                String linea = "";
                DefaultComboBoxModel cbm = (DefaultComboBoxModel) cb_barCodeLibro.getModel();
                cbm.removeAllElements();
                while ((linea = br.readLine()) != null) {
                    System.out.println(linea);
                    try {
                        String datos[] = linea.split(",");
                        barCodes.add(datos[0]);
                        nombresLibros.add(datos[1]);
                        cbm.addElement(datos[0]);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "El archivo cargado no tiene el formato estipulado", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                cb_barCodeLibro.setModel(cbm);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(mainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        pantalla_CreacionLibro.pack();
        pantalla_CreacionLibro.setLocationRelativeTo(null);
        pantalla_CreacionLibro.setAlwaysOnTop(true);
        pantalla_CreacionLibro.setVisible(true);

    }//GEN-LAST:event_menuItem_agregarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Materia;
    private javax.swing.JComboBox<String> cb_barCodeLibro;
    private javax.swing.JComboBox<String> cb_barCodeLibroEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_añadirLibro_A_Inventario;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenuItem menuItem_agregarLibro;
    private javax.swing.JMenuItem menuItem_createAlumno;
    private javax.swing.JMenuItem menuItem_createMaestro;
    private javax.swing.JMenuItem menuItem_devolverLibro;
    private javax.swing.JMenuItem menuItem_edLibri;
    private javax.swing.JMenuItem menuItem_listMaestros;
    private javax.swing.JMenuItem menuItem_loadCSV;
    private javax.swing.JMenuItem menuItem_modAlumno;
    private javax.swing.JMenuItem menuItem_modMaestro;
    private javax.swing.JMenuItem menuItem_newPrestamo;
    private javax.swing.JMenuItem menuItem_readLibrosAprenidzaje;
    private javax.swing.JMenuItem menuItem_readLibrosLectura;
    private javax.swing.JMenu menuLibro;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu menu_readLibros;
    private javax.swing.JFrame pantalla_CreacionLibro;
    private javax.swing.JFrame pantalla_EliminarLibro;
    private javax.swing.JTextArea ta_descrpcionLibro;
    private javax.swing.JTextField tf_nombreLibro;
    private javax.swing.JTextField tf_nombreLibroDelete;
    // End of variables declaration//GEN-END:variables
    private File fichero = null;
    private ArrayList<String> barCodes = new ArrayList<>();
    private ArrayList<String> nombresLibros = new ArrayList<>();
    private ArrayList<Libro> libros = new ArrayList<>();

}
